--Adam Huggins

--Question 1:
SELECT first_name, last_name, dept_code
FROM L_EMPLOYEES
WHERE dept_code in ('SAL', 'SHP', 'ACT');

--Question 2:
SELECT EMPLOYEE_ID, FIRST_NAME, LAST_NAME
FROM L_EMPLOYEES
WHERE EMPLOYEE_ID BETWEEN 201 AND 205;

--Question 3:
SELECT EMPLOYEE_ID, FIRST_NAME, LAST_NAME
FROM L_EMPLOYEES
WHERE TO_CHAR(EMPLOYEE_ID) LIKE '%1%';

--Question 4:
SELECT *
FROM L_EMPLOYEES
WHERE MANAGER_ID IS NULL;

--Question 5:
SELECT DEPARTMENT_NAME AS DEPT
FROM L_DEPARTMENTS
ORDER BY DEPARTMENT_NAME ASC;
